### ISSUE TITLE
ft_strlen : return size_t instead of int

### ISSUE THREAD

**Issue by v3t3a** [QuentinPerez/Maintest#13]
Salut,

Juste une modification pour ne pas devoir modifier le main avant la compilation :
   -> ligne 295 : remplacer le type de variable de "i", de INT, vers SIZE_T

Car strlen return un SIZE_T.
Sinon, j'obtiens l'erreur :

**main.c:299:11: error: comparison of integers of different signs: 'int' and
      'unsigned long' [-Werror,-Wsign-compare]
        while (i < ft_strlen(content))
               ~ ^ ~~~~~~~~~~~~~~~~~~
1 error generated.**

Merci pour le main :+1:

**Comment by QuentinPerez** [comment]
Thanks :)
