### ISSUE TITLE
Bug maintest, aucune trace ?

### ISSUE THREAD

**Issue by Lusoline** [QuentinPerez/Maintest#16]
Hello, lors du test sur la libft le script n'ouvre aucune trace quand on appuie sur B pour obtenir les infos, sachant que j'obtiens l'erreur "An error occured while compiling your program" (ma libft passe a 100% les deux premiers, seul maintest pose souci et je ne peux pas le verifier du coup) 

Merci

**Comment by QuentinPerez** [comment]
Salut, j'imagine que tu utilises le tool de @jgigault, si c'est le cas peux tu voir avec lui sinon donne moi un peu plus de details stp 😊

**Comment by Lusoline** [comment]
En effet, j'utilise le tool, du coup je vais voir ça avec lui directement, merci :).
