### ISSUE TITLE
Dernier test avec l'option -.

### ISSUE THREAD

**Issue by Freccia** [QuentinPerez/Maintest#19]
Mon ft_ls repond bien au tests   `-.`   `-.l`   `-r` en renvoyant un message d'erreur sur stderr, mais quand je test avec le maintest il ne prend pas en compte *ces options, donc il imprime la liste des fichiers dans t_dir:

-> cat your
total 21
-rw-r--r--  1 lfabbro  2015_paris     3 Sep 15 16:33 42
-rw-r--r--  1 lfabbro  2015_paris    16 Sep 15 16:33 .president
lrwxrwxrwx  1 lfabbro  2015_paris     7 Sep 15 16:33 ln_couloir -> couloir
-rw-r--r--  1 lfabbro  2015_paris   759 Sep 15 16:33 couloir
drwxr-xr-x  2 lfabbro  2015_paris  4096 Sep 15 16:33 .
drwxr-xr-x  3 lfabbro  2015_paris  4096 Sep 15 17:17 ..

**Comment by zurbo** [comment]
Je penses aussi que ces tests avec le point fails puisque:
`$ sh diff_me.sh /bin/ls
# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#                                                       :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#          ~ TESTS THAT FAILS IN /bin/ls -1 ~               +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#                                                      #+#    #+#              #
#                                                     ###   ########.fr        #
#                                                                              #
# **************************************************************************** #


Files your and our differ

Error:		 ls -.

1,7c1,2
< total 32
< lrwxr-xr-x  1 tplessis  2015_paris    7 Oct 18 23:39 ln_couloir -> couloir
< -rw-r--r--  1 tplessis  2015_paris  759 Oct 18 23:39 couloir
< -rw-r--r--  1 tplessis  2015_paris    3 Oct 18 23:39 42
< -rw-r--r--  1 tplessis  2015_paris   16 Oct 18 23:39 .president
< drwxr-xr-x  6 tplessis  2015_paris  204 Oct 18 23:39 .
< drwxr-xr-x  7 tplessis  2015_paris  238 Nov 13 00:40 ..
---
> /bin/ls: illegal option -- .
> usage: ls [-ABCFGHLOPRSTUWabcdefghiklmnopqrstuwx1] [file ...]
Files your and our differ

Error:		 ls -l.

1,7c1,2
< total 32
< lrwxr-xr-x  1 tplessis  2015_paris    7 Oct 18 23:39 ln_couloir -> couloir
< -rw-r--r--  1 tplessis  2015_paris  759 Oct 18 23:39 couloir
< -rw-r--r--  1 tplessis  2015_paris    3 Oct 18 23:39 42
< -rw-r--r--  1 tplessis  2015_paris   16 Oct 18 23:39 .president
< drwxr-xr-x  6 tplessis  2015_paris  204 Oct 18 23:39 .
< drwxr-xr-x  7 tplessis  2015_paris  238 Nov 13 00:40 ..
---
> /bin/ls: illegal option -- .
> usage: ls [-ABCFGHLOPRSTUWabcdefghiklmnopqrstuwx1] [file ...]
Files your and our differ

Error:		 ls -.r

1,7c1,2
< total 32
< lrwxr-xr-x  1 tplessis  2015_paris    7 Oct 18 23:39 ln_couloir -> couloir
< -rw-r--r--  1 tplessis  2015_paris  759 Oct 18 23:39 couloir
< -rw-r--r--  1 tplessis  2015_paris    3 Oct 18 23:39 42
< -rw-r--r--  1 tplessis  2015_paris   16 Oct 18 23:39 .president
< drwxr-xr-x  6 tplessis  2015_paris  204 Oct 18 23:39 .
< drwxr-xr-x  7 tplessis  2015_paris  238 Nov 13 00:40 ..
---
> /bin/ls: illegal option -- .
> usage: ls [-ABCFGHLOPRSTUWabcdefghiklmnopqrstuwx1] [file ...]`

(le truc arrive a faill en comparant /bin/ls et /bin/ls)

**Comment by Freccia** [comment]
Bien joue!
