### ISSUE TITLE
I have this bug in the main test in Quentin tests

### ISSUE THREAD

**Issue by cdavilarios** [QuentinPerez/Maintest#24]
./tmp/mymaintest_libft/main.c:307:11: error: comparison of integers of different signs: 'size_t' (aka 'unsigned long') and 'int' [-Werror,-Wsign-compare]
        while (i < ft_strlen(content))
               ~ ^ ~~~~~~~~~~~~~~~~~~
1 error generated.

I know it is because it is comparing i (size_t) with an int (ft_strlen).

**Comment by QuentinPerez** [comment]
Hi @cdavilarios you must change your prototype, strlen returns a size_t `man strlen`
